FROM node:22-alpine AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY ./dist ./dist
COPY .env .env.example ./

RUN npm install -g pnpm
EXPOSE $PORT

FROM build AS production
ENV NODE_ENV=production
RUN pnpm install --prod
CMD ["pnpm", "start"]

FROM build AS development
COPY . .
ENV NODE_ENV=development
RUN pnpm install
CMD ["pnpm", "dev"]