FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json /app
COPY . .

EXPOSE $PORT

FROM build AS production
RUN npm install
RUN npm run build
CMD ["npm", "run", "start"]

FROM build AS development
ENV NODE_ENV=development
RUN npm install
CMD ["npm", "run", "dev"]